name: Latest

on:
  push:
    branches: [ latest ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: cleanup
        run: |
          sudo rm -rf ./.gitignore
          sudo rm -rf ./.github
          sudo rm -rf ./.git
      - name: Get version
        id: version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Pack release
        run: |
          sudo zip -r yuki-magazine.zip . -x "style-premium.css"
          sudo rm -rf ./style.css
          sudo mv ./style-premium.css ./style.css
          sudo zip -r yuki-magazine-premium.zip . -x "yuki-magazine.zip"

      - name: Delete Old Release
        id: delete_release
        uses: dev-drprasad/delete-tag-and-release@v0.1.2
        with:
          delete_release: true # default: false
          tag_name: latest # tag name to delete
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          release_name: latest
          draft: false
          prerelease: true

      - name: Upload Free Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./yuki-magazine.zip
          asset_name: yuki-magazine.zip
          asset_content_type: application/zip

      - name: Upload Premium Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./yuki-magazine-premium.zip
          asset_name: yuki-magazine-premium.zip
          asset_content_type: application/zip
